services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    jalismrs_event_operation.operation_event_subscriber:
        class: 'Jalismrs\Symfony\Bundle\JalismrsOperationEventBundle\EventSubscriber\OperationEventSubscriber'
    
    Jalismrs\Symfony\Bundle\JalismrsOperationEventBundle\EventSubscriber\OperationEventSubscriber: '@jalismrs_event_operation.operation_event_subscriber'
