services:
    _defaults:
        public: false
    
    event_operation.operation_event_subscriber:
        class: 'Jalismrs\EventOperationBundle\OperationEventSubscriber'
    
    Jalismrs\EventOperationBundle\OperationEventSubscriber: '@event_operation.operation_event_subscriber'
