services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    jalismrs_event_operation.operation_event_listener:
        class: 'Jalismrs\Symfony\Bundle\JalismrsOperationEventBundle\EventListener\OperationEventListener'
    
    Jalismrs\Symfony\Bundle\JalismrsOperationEventBundle\EventListener\OperationEventListener: '@jalismrs_event_operation.operation_event_listener'
