services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    event_operation.operation_event_subscriber:
        class: 'Jalismrs\EventOperationBundle\OperationEventSubscriber'
    
    Jalismrs\EventOperationBundle\OperationEventSubscriber: '@event_operation.operation_event_subscriber'
